"""Report direct detector replacement and full 3D checks with evidence boundaries."""
import json,html,shutil
from pathlib import Path
B=Path('/mnt/why/HOT3D/experiments/rfdetr_multidata_v53B_20261007')
def main():
    source=B/'replacement_eval';s=json.loads((source/'statistics.json').read_text());out=B/'review';out.mkdir(exist_ok=True)
    for p in (source/'cases').glob('*.jpg'):shutil.copy2(p,out/p.name)
    proto=json.loads((B/'dataset_protocol.json').read_text());done=json.loads((B/'full/done.json').read_text());dev=json.loads((B/'full/development_status.json').read_text());full=json.loads((B/'full_glove_evaluation.json').read_text()) if (B/'full_glove_evaluation.json').exists() else None
    rows=[]
    for domain,old in s['statistics']['yolo'].items():
        a=s['statistics']['stageA'][domain];b=s['statistics']['stageB'][domain];pair=s['paired_vs_yolo'][domain];precision=f'{old["precision"]:.1%} → {b["precision"]:.1%}' if b['precision_covers_all_hands'] else '标注不覆盖全部手，不当完整精确率'
        rows.append(f'<tr><td>{html.escape(domain)}</td><td>{b["images"]}图 / {b["hands"]}手 / {pair["groups"]}组</td><td>{old["matched"]} ({old["recall"]:.1%})</td><td>{a["matched"]} ({a["recall"]:.1%})</td><td>{b["matched"]} ({b["recall"]:.1%})</td><td>{precision}</td><td>{old["predictions"]} → {b["predictions"]}</td><td>恢复{pair["recovered"]}/{pair["baseline_failed"]}；损失{pair["correct_lost"]}/{pair["baseline_correct"]}</td><td>{pair["recall_delta_CI95"][0]:+.1%}～{pair["recall_delta_CI95"][1]:+.1%}</td></tr>')
    selected=s['selection'];qualification='通过声明的开发门槛，仍需完整留出和3D评估支持' if selected['development_qualified'] else '未通过全部开发门槛，以下StageB为诊断best_trained，不能当安全替换'
    galleries=''.join(f'<figure><img loading="lazy" src="{Path(v["image"]).name}"><figcaption>{html.escape(v["kind"]+" | "+v["dataset"]+" | "+v["id"])}：绿色GT、青色YOLO、洋红RF。{v["points"]}个手框变化。</figcaption></figure>' for v in s['gallery'])
    pose=f'<p>{full["images"]}图 / {full["groups"]}源视频 / {full["hands"]}手 / {full["points"]}人工2D点，实际检出框接入同一完整3D核心。PCK10 {full["SAM_PCK10"]:.1%} → {full["RF_PCK10"]:.1%}，组配对差95% CI {full["paired_source_PCK_delta_CI95"]}；恢复{full["previous_failures_recovered"]}个旧失败点，损失{full["previous_correct_lost"]}/{full["SAM_correct"]}个旧正确点。漏手计失败。只有2D投影真值，不能证明遮挡指尖真实3D深度。</p>' if full else '<p>尚未完成，不能以手框检出改善代替3D改善。</p>'
    training=proto['statistics']['train'];page=f'''<!doctype html><html lang="zh"><meta charset="utf-8"><title>v53 多数据RF-DETR替YOLO</title><style>body{{font:16px system-ui;max-width:1440px;margin:28px auto;padding:0 20px;color:#243040}}p{{line-height:1.75}}table{{border-collapse:collapse;width:100%}}td,th{{padding:10px;border:1px solid #cdd6e3}}img,video{{max-width:100%}}figure{{margin:24px 0}}.note{{background:#fff0d2;padding:16px}}.scroll{{overflow:auto}}</style><h1>多数据 RF-DETR 主手框 + 实例mask → 完整3D</h1><p class="note">{qualification}。默认未替换。100DOH新增400个源视频组是本轮新留出；EgoHands/CPPE/Surgical复用以前测试，只作诊断回放。真实护理视频也不是新盲测。</p><p>StageA四源10轮/4630步；StageB加入6000张100DOH训练图、冻结时已验证的{proto['extra_surgical_verified_train']}张新增Surgical训练图、50张逐图复核无手背景。StageB总采样{training['images']}张、{done['epoch']}轮/{done['step']}步。EgoHands人工实例mask才参与mask监督；其他源只监督手框，CPPE未标裸手不当背景。编码器/检测/分割头共同训练；无人工遮挡。100DOH作者限定非商业研究使用。</p><p>相同在线推理API与GPU：YOLO沿用960/conf0.05/NMS0.7/max100；RF为SegSmall576/BF16，开发选阈值{selected['threshold']}、策略{selected['policy']}。这比较的是两个实际配置，不是同训练预算架构优劣消融。先冻结三套测试预测和哈希，再读新测试XML；测试不用于训练/选权重/阈值。</p><h2>手框：完整检出、正确检出损伤与候选开销</h2><div class="scroll"><table><tr><th>数据</th><th>样本</th><th>YOLO</th><th>RF StageA</th><th>RF StageB</th><th>完整精确率</th><th>预测框数</th><th>恢复/损伤</th><th>召回差95% CI</th></tr>{''.join(rows)}</table></div><p>IoU≥0.5一对一匹配，按源视频/交互对10000次配对bootstrap。CPPE只标手套，Surgical可能存在未标手，未匹配候选不能一概称误检；另测23张逐图复核无手开发背景，并限制医疗域候选总量避免泛滥。</p><h2>重叠子集</h2><pre>{html.escape(json.dumps(s['overlap_proxy'],ensure_ascii=False,indent=2))}</pre><p>这里按标注手框重叠筛选；没有逐指遮挡真值，不能等同于重遮挡手指恢复成功。</p><h2>同一完整3D后端：手套留出</h2>{pose}<p>主YOLO26手框已由RF输出接入；WiLoR内部原有检测器仍用于手侧辅助判断，本轮没有把整套YOLO依赖全部移除。</p><h2>自然恢复与失败</h2>{galleries}<p><a href="statistics.json">封存输出、统计、样本与CI</a> · <a href="dataset_protocol.json">数据与划分</a> · <a href="development_status.json">开发门槛</a> · <a href="full_glove_evaluation.json">完整3D投影检查</a> · <a href="../../DEVELOPMENT_V53.md">简明开发记录</a></p><p>来源：<a href="https://github.com/roboflow/rf-detr">RF-DETR</a>、<a href="https://github.com/ddshan/hand_object_detector">100DOH作者</a>、<a href="https://github.com/MichiganCOG/Surgical_Hands_RELEASE">Surgical Hands</a>、<a href="https://vision.soic.indiana.edu/projects/egohands/">EgoHands</a>。</p></html>'''
    (out/'report.html').write_text(page,encoding='utf-8')
    for name,path in [('statistics.json',source/'statistics.json'),('dataset_protocol.json',B/'dataset_protocol.json'),('development_status.json',B/'full/development_status.json'),('full_glove_evaluation.json',B/'full_glove_evaluation.json')]:
        if path.exists():shutil.copy2(path,out/name)
    print('REPORT',out/'report.html',flush=True)
if __name__=='__main__':main()
